=== jvshahid/nekodtd/data/dtd/test.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--Generated from data\dtd\test.dtd--><xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"><!--<!ELEMENT root (foo|(bar,baz)+)*>--><xsd:element name="root"><xsd:complexType><xsd:choice minOccurs="0" maxOccurs="unbounded"><xsd:element ref="foo"/><xsd:sequence minOccurs="1" maxOccurs="unbounded"><xsd:element ref="bar"/><xsd:element ref="baz"/></xsd:sequence></xsd:choice><!--<!ATTLIST root version CDATA #FIXED "1.0">--><xsd:attribute name="version" fixed="1.0"><xsd:simpleType><xsd:restriction base="xsd:string"/></xsd:simpleType></xsd:attribute></xsd:complexType></xsd:element><!--<!ELEMENT foo EMPTY>--><xsd:element name="foo"><xsd:complexType/></xsd:element><!--<!ELEMENT bar (#PCDATA)>--><xsd:element name="bar"><xsd:complexType mixed="true"/></xsd:element><!--<!ELEMENT baz (#PCDATA|mumble)*>--><xsd:element name="baz"><xsd:complexType mixed="true"><xsd:choice maxOccurs="unbounded" minOccurs="0"><xsd:element ref="mumble"/></xsd:choice></xsd:complexType></xsd:element><!--<!ELEMENT mumble ANY>--><xsd:element name="mumble"><xsd:complexType mixed="true"><xsd:choice maxOccurs="unbounded" minOccurs="0"><xsd:element ref="bar"/><xsd:element ref="baz"/><xsd:element ref="foo"/><xsd:element ref="mumble"/><xsd:element ref="root"/></xsd:choice></xsd:complexType></xsd:element></xsd:schema>

=== jvshahid/nekodtd/data/dtd/test-schema.xml
<root xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' 
      xsi:noNamespaceSchemaLocation='test.xsd'>
 <bar>text1</bar>
 <baz>text2</baz>
 <foo/>
 <bar>text3</bar>
 <baz>text4</baz>
 <bar>text5</bar>
 <baz><mumble>text5<foo/></mumble></baz>
</root>
