=== jvshahid/nekodtd/data/dtd/test.dtd
<!ELEMENT root (foo|(bar,baz)+)*>
<!ATTLIST root version CDATA #FIXED '1.0'>
<!ELEMENT foo EMPTY>
<!ELEMENT bar (#PCDATA)>
<!ELEMENT baz (#PCDATA|mumble)*>
<!ELEMENT mumble ANY>

=== jvshahid/nekodtd/data/dtd/test.xml
<!DOCTYPE root SYSTEM 'test.dtd'>
<root>
 <bar>text1</bar>
 <baz>text2</baz>
 <foo/>
 <bar>text3</bar>
 <baz>text4</baz>
 <bar>text5</bar>
 <baz><mumble>text5<foo/></mumble></baz>
</root>
